### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by bahadirarslan** [srujanmhase/reward_popup#1]
Your widget looks promising but it is not working.
Because you forgot to add LottieAnimation `animation_ljy5rgiq.json`

If you add this to the package or guide, we can use.

Also please consider this, `showRewardPopup` should be Future. Because we have to let users see this animation and after users dismiss the pop-up we can navigate to other screens. I would like to contribute if I can but I can not run without the animation file.

**Comment by srujanmhase** [comment]
Hi @bahadirarslan , sorry for the oversight. I have made the necessary changes: made it a future so it can return a value as well as included the file itself in the assets.

One thing however, I cannot get the animation to load. Since I have included the file, can you try to contribute & make it work?

**Comment by bahadirarslan** [comment]
Hi,

Finally, I made it work. I had never tried to access assets files in a package and realized it was a little bit confusing.  
Anyway, now it works, here is the solution I found https://stackoverflow.com/a/69897811/423699
I sent you a PR

Thank you, you made it the future but how users will dismiss this animation? There should be a way, maybe options
- enableTapToDismiss : when enabled if animation is tapped it is dismissed and future returns.
- showCloseButton: when enabled shows an X button
